on:
  push:
    tags:
      - v*

name: Dockerhub Push

jobs:
  dockerhub-push:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v2

    - name: Build the Docker image
      run:  |
        tagVer=$(basename "${{ github.ref }}")
        semVer=${tagVer:1}
        docker build . --file Dockerfile --tag vmware/powerclicore:${semVer}

    - name: Dockerhub push
      run: |
        tagVer=$(basename "${{ github.ref }}")
        semVer=${tagVer:1}
        docker login -u ${{ secrets.DOCKERHUB_USER }} -p ${{ secrets.DOCKERHUB_TOKEN }}
        docker tag vmware/powerclicore:${semVer} vmware/powerclicore:latest
        docker push vmware/powerclicore:${semVer}
        docker push vmware/powerclicore:latest
